data_ingestion:
  ticker: "MSFT"
  num_days: 5000
  raw_data_dir: "artifacts/data/raw_data"

base_model:
  input_size: 5          # [Open, High, Low, Close, Volume]
  hidden_size: 128
  num_layers: 2
  dropout: 0.2
  bidirectional: False   # For potential future enhancement
  batch_size: 32
  base_model_path: "artifacts/model"
  seed: 8

data_preprocessing:
  processed_file_path: "artifacts/data/processed_data"
  sequence_length: 60
  train_size: 0.8
  test_size: 0.1
  val_size: 0.1
  batch_size: 32
  features: ["Open", "High", "Low", "Close", "Volume"]
  # features: ["Close"]
  target: "Close"
  normalize: True
  fill_method: "ffill"
  seed: 8

training:
  learning_rate: 0.0005
  weight_decay: 5e-4
  epochs: 100
  optimizer: "adamw"
  lr_patience: 7
  lr_factor: 0.3
  gradient_clip: 1.5
  early_stopping_patience: 25
  checkpoint_dir: "artifacts/model"
  checkpoint_freq: 20
  seed: 8

evaluation:
  metrics: {
    "MeanAbsoluteError": True,
    "RootMeanSquaredError": True,
    "R^2": True,
    "MeanAbsolutePercentageError": True,
    "DirectionalAccuracy": True,
    "MagCorr": True,
    "SharpeRatio": True,
  }
  log_model: True
  save_graph: True
